### ISSUE TITLE
Rebooting Tunnels

### ISSUE THREAD

**Issue by futurealecks** [robgil/vyos-vpc#1]
Robgil,

Thanks for putting this out there. I have several VyOs routers that touch AWS and have had trouble with NAT. When you enable NAT traversal and reboot one of your VyOs routers does your tunnels automatically come up?

I've experienced the tunnels not coming up with both VyOs and Brocade vRouter within AWS.

**Comment by robgil** [comment]
I haven't run in to this, but haven't had the chance to run in a "production" like environment. I'm setting up new tunnels now and will let you know what happens after reboot. Apologies for the late reply.

**Comment by robgil** [comment]
I have not had issues after reboot. I do see tunnels occasionally do not automatically reconnect during network failures. I end up having to reset those peers, but otherwise its relatively stable.
